apiVersion: v1
kind: Pod
metadata:
  name: test-pod-kubedsm
  namespace: ecmus
  labels:
    app: test-kubedsm
    tier: edge
    nodetype: edge
spec:
  schedulerName: kubedsm
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
